#ifndef OPEN_BMS_CLAW_CONFIG_APP_CONFIG_H
#define OPEN_BMS_CLAW_CONFIG_APP_CONFIG_H

#define APP_ENABLE_BRINGUP_SERVICE 1
#define APP_ENABLE_BMS_SERVICE 0
#define APP_ENABLE_POWER_SERVICE 0
#define APP_ENABLE_PROTOCOL_SERVICE 0
#define APP_ENABLE_UI_SERVICE 1
#define APP_ENABLE_TEMPERATURE_ALARM_SAMPLE 0

#endif
