#ifndef OPEN_BMS_CLAW_CONFIG_FEATURE_CONFIG_H
#define OPEN_BMS_CLAW_CONFIG_FEATURE_CONFIG_H

#define FEATURE_ENABLE_STATUS_LED 0
#define FEATURE_ENABLE_UART_LOG 1
#define FEATURE_ENABLE_ADC_PROBE 1
#define FEATURE_ENABLE_I2C_PROBE 1

#define FEATURE_ENABLE_BMS 0
#define FEATURE_ENABLE_POWER 0
#define FEATURE_ENABLE_PROTOCOL 0

#endif
